### ISSUE TITLE
Tracking: V3 Support

### ISSUE THREAD

**Issue by Fernthedev** [bsq-ports/Chroma#32]
- [x] Most key renames (`_lightId` -> `lightId`)
- [x] Custom Components
  - [x] Bloom fog in v3 (?)
  - [x] TubeBloomLight
  - [x] LightID
  - [x] AnimateComponent
    - [x] Rewrite Tracks to delegate properties definition to mods?
- [x] Note spawn effect
- [x] Arc/Chain coloring

Chroma v2 features -> v3 have been tested for the most part, which seem to be ok. However the v3 exclusive functionality, specifically sliders/arc coloring has not been tested.

**Comment by Nitai610** [comment]
arc coloring not working: https://beatsaver.com/maps/2b5ee

**Comment by Elecast2** [comment]
BloomFogEnvironment seems to still not be working correctly, here is a comparison video of pc and quest2 of my map: https://youtu.be/dKklq1WjUzw
I used this setting for the fog:

<code>
        "id": "[0]Environment",
        "lookupMethod": "EndsWith",
        "components": {
            "BloomFogEnvironment": {
                "height": 200,
                "startY": -600,
                "attenuation": 0.0002
            }
        }
</code>

All the lights in the Noria are made using the geometry, and OpaqueLight shader for the material. and use components for the bloom fog. here is an example:
<code>
{
  "geometry": {
    "type":"Cube","material":"lightcube_material"
},
  "components": {
  "TubeBloomPrePassLight": {
      "colorAlphaMultiplier":10.0,
      "bloomFogIntensityMultiplier":20.0
}
</code>

**Comment by Elecast2** [comment]
Extra note: I just noticed in the video comparison that lockRotation property of the rotation lights may not be working too on quest. In some parts it uses lockRotation that works well on PC but lights rotate randomly on quest 2

**Comment by Fernthedev** [comment]
V3 Support is implemented. Stability is another question though.
Closing this to leave room for v3 feature specific bug reports.
